# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trustylib-Integration-ObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trustylib-Integration-ObjectiveC
pod 'Trustylib', '~> 1.0.0'

end
