# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Trustylib-Integration-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for Trustylib-Integration-SwiftUI
  use_frameworks! :linkage => :static
  pod 'Trustylib', :path => '../../'

end
